package info.vanderkooy.ucheck;

import java.util.Map;
import com.google.common.collect.BiMap;
import com.google.common.collect.HashBiMap;

public class Meta {
	public static Map<String, String> getStudieLijst() {
		BiMap<String, String> studieLijst = HashBiMap.create();
		
		studieLijst.put("ALG", "Algemeen vakgebied");
		studieLijst.put("ARAB", "Arabische talen en culturen");
		studieLijst.put("ARCH", "Archeologie en prehistorie");
		studieLijst.put("ASA", "Area Studies Asia");
		studieLijst.put("BSKE", "Bestuurskunde");
		studieLijst.put("BFW", "Bio-farmaceutische wetenschap");
		studieLijst.put("BIO", "Biologie");
		studieLijst.put("BIOM", "Biomedische wetenschappen");
		studieLijst.put("BOEK", "Boek en digitale media");
		studieLijst.put("CHE", "Chemistry");
		studieLijst.put("CLANEC", "Classics Ancient Near East Civ");
		studieLijst.put("CANS", "Cult. antropologie ontw. soc.");
		studieLijst.put("DUITS", "Duitse taal en cultuur");
		studieLijst.put("DUTCHST", "Dutch Studies (Nederlandkunde)");
		studieLijst.put("EGYPTE", "Egyptische taal en cultuur");
		studieLijst.put("ENGELS", "Engelse taal en cultuur");
		studieLijst.put("EUS", "European Union Studies");
		studieLijst.put("FGWALG", "FGW Algemeen");
		studieLijst.put("W&N", "Faculteit W&N");
		studieLijst.put("PHOTOGS", "Film and Photographic studies");
		studieLijst.put("FRANS", "Franse taal en cultuur");
		studieLijst.put("GNK", "Geneeskunde");
		studieLijst.put("GS", "Geschiedenis");
		studieLijst.put("GODG", "Godgeleerdheid");
		studieLijst.put("GRIEKLAT", "Griekse Latijnse Taal & Cult.");
		studieLijst.put("HJS", "Hebreeuwse en Joodse Studies");
		studieLijst.put("HERV", "Hervormde Kerk");
		studieLijst.put("INDECO", "Industrial Ecology");
		studieLijst.put("INF", "Informatica");
		studieLijst.put("ISLM", "Islamic Studies");
		studieLijst.put("ISLT", "Islamitische theologie");
		studieLijst.put("ITAL", "Italiaanse taal en cultuur");
		studieLijst.put("JOURNIME", "Journalistiek en nieuwe media");
		studieLijst.put("FGWKERN", "Kerncurriculum FGW");
		studieLijst.put("FDK", "Kunsten");
		studieLijst.put("KG", "Kunstgeschiedenis");
		studieLijst.put("LAAS", "Latin American Amerindian Stud");
		studieLijst.put("LEIALG", "Leiden algemeen");
		studieLijst.put("LO", "Lerarenopleiding");
		studieLijst.put("FLEBYVAK", "Letteren Bijvak");
		studieLijst.put("FLEALG", "Letteren algemeen");
		studieLijst.put("LETTERK", "Letterkunde");
		studieLijst.put("LA%26S", "Liberal Arts & Sciences");
		studieLijst.put("LST", "Life Science and technology");
		studieLijst.put("LITW", "Literatuurwetenschap");
		studieLijst.put("MANAGEME", "Management");
		studieLijst.put("MIDOOST", "Midden Oosten Studies");
		studieLijst.put("MST", "Molecular science &Technology");
		studieLijst.put("MUZIEK", "Muziek");
		studieLijst.put("NSC", "Nanoscience");
		studieLijst.put("NTK", "Natuurkunde");
		studieLijst.put("NED", "Nederlandse taal en cultuur");
		studieLijst.put("NP", "Nieuwperzische taal en cultuur");
		studieLijst.put("OCMW", "Oude Culturen van de Mediter W");
		studieLijst.put("PEDA", "Pedagogische wetenschappen");
		studieLijst.put("POWE", "Politicologie");
		studieLijst.put("PKST", "Praktijkstudies");
		studieLijst.put("PREUNIV", "Pre-university");
		studieLijst.put("PSYC", "Psychologie");
		studieLijst.put("LAW", "Rechten");
		studieLijst.put("SEMI", "Semitische talen en culturen");
		studieLijst.put("SLAV", "Slavische talen cult/Ruslandk.");
		studieLijst.put("STK", "Sterrenkunde");
		studieLijst.put("TCIA", "T&C van Indiaans Amerika");
		studieLijst.put("TCMA", "T&C van Mesopota & Anatolië");
		studieLijst.put("TAALK", "Taalkunde");
		studieLijst.put("TW", "Taalwetenschap");
		studieLijst.put("INDTIBET", "Talen en Cult. India en Tibet");
		studieLijst.put("INDONES", "Talen en Culturen Indonesië");
		studieLijst.put("AFRIKA", "Talen en Culturen van Afrika");
		studieLijst.put("TCLA", "Talen en culturen Latijns Am");
		studieLijst.put("CHINA", "Talen en culturen van China");
		studieLijst.put("JAPAN", "Talen en culturen van Japan");
		studieLijst.put("KOREA", "Talen en culturen van Korea");
		studieLijst.put("TCC", "Talencentrum: Communicatie");
		studieLijst.put("THEA", "Theater- en filmwetenschap");
		studieLijst.put("TURK", "Turkse talen en culturen");
		studieLijst.put("VIET", "Vergelijkende Indo-Europese TW");
		studieLijst.put("VTW", "Vergelijkende Taalwetenschap");
		studieLijst.put("LAVA", "Vitality and ageing");
		studieLijst.put("WYSB", "Wijsbegeerte");
		studieLijst.put("WSK", "Wiskunde");
		studieLijst.put("ZZOAZIE", "Zuid en Zuid-Oost Azië");
		
		return studieLijst;
	}
}
